Thu Dec 14 23:03:14 2017 kern.debug kernel: [23917.573685] UDP: bad checksum. From 117.91.7.99:39830 to 10.52.229.90:20067 ulen 159
Thu Dec 14 23:04:28 2017 daemon.warn zabbix_agentd[4140]: active check configuration update from [192.168.10.2:1234] started to fail (ZBX_TCP_READ() failed: [4] Interrupted system call)
Thu Dec 14 23:05:28 2017 daemon.warn zabbix_agentd[4140]: active check configuration update from [192.168.10.2:1234] is working again
Thu Dec 14 23:05:28 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.in[vth31,bytes]" is not supported
Thu Dec 14 23:05:28 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.in[vth31]" is not supported
Thu Dec 14 23:05:28 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.out[vth31,bytes]" is not supported
Thu Dec 14 23:05:28 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.out[vth31]" is not supported
Thu Dec 14 23:05:28 2017 daemon.warn zabbix_agentd[4140]: Remote command [who | wc -l] result is not unsigned integer
Thu Dec 14 23:05:28 2017 daemon.warn zabbix_agentd[4140]: active check "system.users.num" is not supported
Thu Dec 14 23:07:28 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.in[vth31,bytes]" is not supported
Thu Dec 14 23:07:31 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.in[vth31]" is not supported
Thu Dec 14 23:07:31 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.out[vth31,bytes]" is not supported
Thu Dec 14 23:07:31 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.out[vth31]" is not supported
Thu Dec 14 23:07:31 2017 daemon.warn zabbix_agentd[4140]: Remote command [who | wc -l] result is not unsigned integer
Thu Dec 14 23:07:31 2017 daemon.warn zabbix_agentd[4140]: active check "system.users.num" is not supported
Thu Dec 14 23:09:31 2017 daemon.warn zabbix_agentd[4140]: active check configuration update from [192.168.10.2:1234] started to fail (ZBX_TCP_READ() failed: [4] Interrupted system call)
Thu Dec 14 23:10:32 2017 daemon.warn zabbix_agentd[4140]: active check configuration update from [192.168.10.2:1234] is working again
Thu Dec 14 23:16:38 2017 daemon.warn zabbix_agentd[4140]: active check configuration update from [192.168.10.2:1234] started to fail (ZBX_TCP_READ() failed: [4] Interrupted system call)
Thu Dec 14 23:17:38 2017 daemon.warn zabbix_agentd[4140]: active check configuration update from [192.168.10.2:1234] is working again
Thu Dec 14 23:17:38 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.in[vth31,bytes]" is not supported
Thu Dec 14 23:17:38 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.in[vth31]" is not supported
Thu Dec 14 23:17:38 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.out[vth31,bytes]" is not supported
Thu Dec 14 23:17:38 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.out[vth31]" is not supported
Thu Dec 14 23:17:38 2017 daemon.warn zabbix_agentd[4140]: Remote command [who | wc -l] result is not unsigned integer
Thu Dec 14 23:17:38 2017 daemon.warn zabbix_agentd[4140]: active check "system.users.num" is not supported
Thu Dec 14 23:27:38 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.in[vth31,bytes]" is not supported
Thu Dec 14 23:27:38 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.in[vth31]" is not supported
Thu Dec 14 23:27:38 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.out[vth31,bytes]" is not supported
Thu Dec 14 23:27:38 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.out[vth31]" is not supported
Thu Dec 14 23:27:38 2017 daemon.warn zabbix_agentd[4140]: Remote command [who | wc -l] result is not unsigned integer
Thu Dec 14 23:27:38 2017 daemon.warn zabbix_agentd[4140]: active check "system.users.num" is not supported
Thu Dec 14 23:37:39 2017 daemon.err zabbix_agentd[4140]: cannot parse list of active checks: cannot parse as a valid JSON object: invalid object format, expected opening character '{' at: ',{"key":"net.if.out[vth11]","delay":30,"lastlogsize":0,"mtime":0},{"key":"net.if.out[vth21,bytes]","delay":30,"lastlogsize":0,"mtime":0},{"key":"net.if.out[vt
Thu Dec 14 23:39:40 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.in[vth31,bytes]" is not supported
Thu Dec 14 23:39:40 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.in[vth31]" is not supported
Thu Dec 14 23:39:40 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.out[vth31,bytes]" is not supported
Thu Dec 14 23:39:40 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.out[vth31]" is not supported
Thu Dec 14 23:39:40 2017 daemon.warn zabbix_agentd[4140]: Remote command [who | wc -l] result is not unsigned integer
Thu Dec 14 23:39:40 2017 daemon.warn zabbix_agentd[4140]: active check "system.users.num" is not supported
Thu Dec 14 23:46:19 2017 daemon.notice openvpn(client)[4135]: TLS: tls_process: killed expiring key
Thu Dec 14 23:46:37 2017 daemon.notice openvpn(client)[4135]: TLS: soft reset sec=0 bytes=86878/0 pkts=1654/0
Thu Dec 14 23:46:37 2017 daemon.notice openvpn(client)[4135]: VERIFY OK: depth=1, C=CN, ST=BJ, L=BeiJing, O=CRTT, OU=crwifi, CN=CRTT CA, name=vpn-crwifi, emailAddress=crwifi@crtt.com
Thu Dec 14 23:46:37 2017 daemon.notice openvpn(client)[4135]: VERIFY OK: nsCertType=SERVER
Thu Dec 14 23:46:37 2017 daemon.notice openvpn(client)[4135]: VERIFY OK: depth=0, C=CN, ST=BJ, L=BeiJing, O=CRTT, OU=crwifi, CN=vpn-crwifi, name=vpn-crwifi, emailAddress=crwifi@crtt.com
Thu Dec 14 23:46:38 2017 daemon.notice openvpn(client)[4135]: Data Channel Encrypt: Cipher 'BF-CBC' initialized with 128 bit key
Thu Dec 14 23:46:38 2017 daemon.notice openvpn(client)[4135]: Data Channel Encrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
Thu Dec 14 23:46:38 2017 daemon.notice openvpn(client)[4135]: Data Channel Decrypt: Cipher 'BF-CBC' initialized with 128 bit key
Thu Dec 14 23:46:38 2017 daemon.notice openvpn(client)[4135]: Data Channel Decrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
Thu Dec 14 23:46:38 2017 daemon.notice openvpn(client)[4135]: Control Channel: TLSv1, cipher TLSv1/SSLv3 DHE-RSA-AES256-SHA, 2048 bit RSA
Thu Dec 14 23:49:40 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.in[vth31,bytes]" is not supported
Thu Dec 14 23:49:40 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.in[vth31]" is not supported
Thu Dec 14 23:49:40 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.out[vth31,bytes]" is not supported
Thu Dec 14 23:49:40 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.out[vth31]" is not supported
Thu Dec 14 23:49:40 2017 daemon.warn zabbix_agentd[4140]: Remote command [who | wc -l] result is not unsigned integer
Thu Dec 14 23:49:40 2017 daemon.warn zabbix_agentd[4140]: active check "system.users.num" is not supported
Thu Dec 14 22:42:24 2017 daemon.err zabbix_agentd[4140]: cannot parse list of active checks: cannot parse as a valid JSON object: invalid object format, expected opening character '{' at: ',{"key":"net.if.out[vth11]","delay":30,"lastlogsize":0,"mtime":0},{"key":"net.if.out[vth21,bytes]","delay":30,"lastlogsize":0,"mtime":0},{"key":"net.if.out[vt
Thu Dec 14 22:44:24 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.in[vth31,bytes]" is not supported
Thu Dec 14 22:44:24 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.in[vth31]" is not supported
Thu Dec 14 22:44:24 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.out[vth31,bytes]" is not supported
Thu Dec 14 22:44:24 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.out[vth31]" is not supported
Thu Dec 14 22:44:24 2017 daemon.warn zabbix_agentd[4140]: Remote command [who | wc -l] result is not unsigned integer
Thu Dec 14 22:44:24 2017 daemon.warn zabbix_agentd[4140]: active check "system.users.num" is not supported
Thu Dec 14 22:45:23 2017 kern.debug kernel: [22845.028890] UDP: bad checksum. From 182.91.41.254:27080 to 10.6.245.113:1135 ulen 1133
Thu Dec 14 22:46:18 2017 daemon.notice openvpn(client)[4135]: TLS: tls_process: killed expiring key
Thu Dec 14 22:46:19 2017 daemon.notice openvpn(client)[4135]: TLS: soft reset sec=0 bytes=88383/0 pkts=1683/0
Thu Dec 14 22:46:25 2017 daemon.notice openvpn(client)[4135]: VERIFY OK: depth=1, C=CN, ST=BJ, L=BeiJing, O=CRTT, OU=crwifi, CN=CRTT CA, name=vpn-crwifi, emailAddress=crwifi@crtt.com
Thu Dec 14 22:46:25 2017 daemon.notice openvpn(client)[4135]: VERIFY OK: nsCertType=SERVER
Thu Dec 14 22:46:25 2017 daemon.notice openvpn(client)[4135]: VERIFY OK: depth=0, C=CN, ST=BJ, L=BeiJing, O=CRTT, OU=crwifi, CN=vpn-crwifi, name=vpn-crwifi, emailAddress=crwifi@crtt.com
Thu Dec 14 22:46:37 2017 daemon.notice openvpn(client)[4135]: Data Channel Encrypt: Cipher 'BF-CBC' initialized with 128 bit key
Thu Dec 14 22:46:37 2017 daemon.notice openvpn(client)[4135]: Data Channel Encrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
Thu Dec 14 22:46:37 2017 daemon.notice openvpn(client)[4135]: Data Channel Decrypt: Cipher 'BF-CBC' initialized with 128 bit key
Thu Dec 14 22:46:37 2017 daemon.notice openvpn(client)[4135]: Data Channel Decrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
Thu Dec 14 22:46:37 2017 daemon.notice openvpn(client)[4135]: Control Channel: TLSv1, cipher TLSv1/SSLv3 DHE-RSA-AES256-SHA, 2048 bit RSA
Thu Dec 14 22:54:24 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.in[vth31,bytes]" is not supported
Thu Dec 14 22:54:25 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.in[vth31]" is not supported
Thu Dec 14 22:54:25 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.out[vth31,bytes]" is not supported
Thu Dec 14 22:54:25 2017 daemon.warn zabbix_agentd[4140]: active check "net.if.out[vth31]" is not supported
Thu Dec 14 22:54:25 2017 daemon.warn zabbix_agentd[4140]: Remote command [who | wc -l] result is not unsigned integer
Thu Dec 14 22:54:25 2017 daemon.warn zabbix_agentd[4140]: active check "system.users.num" is not supported
